export const REGISTER_IN_PROGRESS = 'REGISTER_IN_PROGRESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_ME_SUCCESS = 'GET_ME_SUCCESS';
export const GET_ME_FAILURE = 'GET_ME_FAILURE';

export const LOGOUT = 'LOGOUT';

export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE';

export const UPLOAD_IMAGES_REQUEST = 'UPLOAD_IMAGES_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';

export const SET_SELECT_IMAGE = 'SET_SELECT_IMAGE';

export const DELETE_IMAGES_SUCCESS = 'DELETE_IMAGES_SUCCESS';

export const CLEAR_IMAGES = 'CLEAR_IMAGES';

export const UPLOADING_PROGRESS_OPEN = 'UPLOADING_PROGRESS_OPEN';
export const UPLOADING_PROGRESS_CLOSE = 'UPLOADING_PROGRESS_CLOSE';

export const SET_SHOW_LOADER = 'SET_SHOW_LOADER';

export const GET_LABEL_SUCCESS = 'GET_LABEL_SUCCESS';
export const SET_TEMP_LABEL = 'SET_TEMP_LABEL';
export const SET_TEMP_SEARCH_TEXT = 'SET_TEMP_SEARCH_TEXT';
export const SYNC_SEARCH_QUERY = 'SYNC_SEARCH_QUERY';
